### ISSUE TITLE
Storage: merge table

### ISSUE THREAD

**Issue by myxo** [myxo/ssyp_db#50]
Нужно дбавить в интерфейс `ITableList` функцию `MergeTable(std::vector<size_t> merged_tables, std::string result_table)`, которая заменит таблицы с индексами из `merged_tables` на новую таблицу `result_table`.

Для начала можно реализовать для InMemory базы, чтобы можно было начать писать код со стороны Datamodel

Нужно для #6

**Comment by myxo** [comment]
В рамках этого пункта можно не реализовывать удаление ненужных таблиц (для этого есть #30 )

**Comment by siw321** [comment]
Как объединять таблицы, если для ITableList это просто строки?

**Comment by myxo** [comment]
Тебе не нужно ничего объединять, это работа Datamodel.
Твоя задача в том, чтобы после вызова этой функции новые ITableList не показывали таблицы, которые "удалили", а вместо них была новая
